name: Build e Push Imagem Docker

on:
  push:
    tags:
      - 'v*'   # dispara só em tags do tipo v1.2.3

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem versionada
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: raicasale/projeto-versionamento:${{ github.ref_name }}

      - name: Update latest tag if newer
        uses: imjasonh/update-latest-docker-tag@v1
        with:
          image: raicasale/projeto-versionamento
          tag: ${{ github.ref_name }}
          registry-user: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
